apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "bear.52.214.225.250.nip.io"
    http:
      paths:
      - backend:
          service:
            name: bear-svc
            port:
              number: 80
        path: /
        pathType: Prefix
