apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2 # We strip the prefix before it passes to our backend or our app wont load as it will get route /bears instead /
spec:
  ingressClassName: nginx
  rules:
  - host: "*.52.214.225.250.nip.io"
    http:
      paths:
      - path: /bear
        pathType: Prefix
        backend:
          service:
            name: bear-svc
            port:
              number: 80
